// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function ImportFile(arg1) {
  return window['go']['main']['App']['ImportFile'](arg1);
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function WriteLog(arg1) {
  return window['go']['main']['App']['WriteLog'](arg1);
}
