// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToClipboard(arg1:string):Promise<boolean>;

export function ImportFile(arg1:string):Promise<string>;

export function LoadFile():Promise<string>;
